id: avmEventResponder
name: AVM Event Responder
description: AVM Event Responder
resource: repository
disabled: false

configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: 'If a new issue or PR is opened add the "Needs: Triage :mag:" label'
        if:
          - or:
              - payloadType: Issues
              - payloadType: Pull_Request
          - isAction:
              action: Opened
        then:
          - addLabel:
              label: "Needs: Triage :mag:"

      - description: 'Azure Policy label'
        if:
          - payloadType: Issues
          - isAction:
              action: Opened
          - bodyContains:
              pattern: |
                ### Which product are you raising for?

                Azure Policy
        then:
          - addLabel:
              label: "Product: Azure Policy :shield:"
