name: Feature Request
description: File a feature request for Azure landing zone tools or guidance
title: "[Feature Request]: "
labels: ["Needs: Triage :mag:"]
projects: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request, please try to include as much detail as possible to help us understand your ask. Also please try to include a "why" in the ask.
  - type: dropdown
    id: product
    attributes:
      label: Which product are you raising for?
      description: You can select multiple items, if required, just keep opening the dropdown and selecting items
      multiple: true
      options:
        - Azure Policy
        - ALZ Portal Experience
        - ALZ Terraform (Classic)
        - ALZ Terraform (AVM)
        - ALZ Bicep (Classic)
        - ALZ Bicep (AVM)
        - ALZ PowerShell Module (Accelerator)
        - Sub/LZ Vending
        - Sub/LZ Vending (TF)
        - Sub/LZ Vending (Bicep)
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What is the feature request?
      description: "Please provide a clear and concise description of what the feature request is."
      placeholder: "E.g. As a user of ALZ tool XYZ I would like the ability to do ABC..."
    validations:
      required: true
  - type: textarea
    id: potential
    attributes:
      label: Potential implementation/configuration
      description: "(Optional) Please provide an example implementation/configuration of your feature request or the changes you'd like made"
      render: Text
    validations:
      required: false




